
// Objective-C API for talking to the following Go packages
//
//	test/gosocket
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Gosocket_FRAMEWORK_H__
#define __Gosocket_FRAMEWORK_H__

#include "Gosocket.objc.h"
#include "Universe.objc.h"

#endif
