// Objective-C API for talking to test/gosocket Go package.
//   gobind -lang=objc test/gosocket
//
// File is generated by gobind. Do not edit.

#ifndef __Gosocket_H__
#define __Gosocket_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT void GosocketRun(NSString* _Nullable path);

#endif
